# This is a template file for application.yml, which should contain the list
# of required keys, but NOT the secret values.

# Please, maintain this file up to date with the list of required keys for the application,
# with non-secret values, this way your collaborators will known when
# a new key is required in their own application.yml.

# Because this is file is shared,
# DO NOT PUT ANY SECRET VALUE HERE, ONLY THE LIST OF REQUIRED KEYS and public values.
# Use application.yml to set the whole key + values.

# Examples:
#
# CLOUDINARY_URL: "" # This means "You need a secret CLOUDINARY_URL in your application.yml"
#
# development:
#   HOST: 'localhost:3000' # This is not a secret value, I can write it.
#
